<?xml version="1.0" ?>
<robot name="turtlebot3_waffle_sim" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find turtlebot3_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find turtlebot3_description)/urdf/turtlebot3_waffle.gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.005"/>
  <xacro:property name="r200_cam_rgb_py" value="0.018"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.013"/>
  <xacro:property name="r200_cam_depth_offset" value="0.01"/>

  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="0.01" /> <!-- arbitrary value for mass -->
  <xacro:property name="base_offset" value="-0.064" /> <!-- base link offset -->
  <xacro:property name="width" value="0.01" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="width2" value="0.266" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="0.11" /> <!-- Link 1 -->
  <xacro:property name="height2" value="0.1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="0.05" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.01" /> <!-- Space btw top of beam and the each joint -->





  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.010" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0.064 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/bases/waffle_base.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="-0.064 0 0.047" rpy="0 0 0"/>
      <geometry>
        <box size="0.266 0.266 0.094"/>
      </geometry>
    </collision>
    
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="1.3729096e+00"/>
      <inertia ixx="8.7002718e-03" ixy="-4.7576583e-05" ixz="1.1160499e-04"
               iyy="8.6195418e-03" iyz="-3.5422299e-06"
               izz="1.4612727e-02" />
    </inertial>
  </link>



  <joint name="joint1" type="fixed">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="${base_offset+0.133+width*2} 0 ${width+0.094}" rpy="0 -3.14 0"/>
  </joint>


<link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width2} ${height1}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width2} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>




  <joint name="left_suspension_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="left_suspension_link"/>
    <origin xyz="0.0 0.154 -0.01" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.04" upper="0" effort="1000" velocity="1000"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="left_suspension_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.001" radius="0.001"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-01" />
      <inertia ixx="1.1175580e-02" ixy="0.0" ixz="0.0"
               iyy="1.1192413e-02" iyz="0.0"
               izz="2.0712558e-02" />
    </inertial>
  </link>


  <joint name="wheel_left_joint" type="continuous">
    <parent link="left_suspension_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/left_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-01" />
      <inertia ixx="1.1175580e-02" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-02" iyz="-1.4400107e-11"
               izz="2.0712558e-02" />
      </inertial>
  </link>

  <joint name="right_suspension_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="right_suspension_link"/>
    <origin xyz="0.0 -0.154 -0.01" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.04" upper="0" effort="1000" velocity="1000"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="right_suspension_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.001" radius="0.001"/>
      </geometry>
    </visual>
    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-01" />
      <inertia ixx="1.1175580e-02" ixy="0.0" ixz="0.0"
               iyy="1.1192413e-02" iyz="0.0"
               izz="2.0712558e-02" />
    </inertial>
  </link>



  <joint name="wheel_right_joint" type="continuous">
    <parent link="right_suspension_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 0.0 0.0" rpy="-1.57 0 0"/>
    <axis xyz="0 0 1"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/wheels/right_tire.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.018" radius="0.033"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-01" />
      <inertia ixx="1.1175580e-02" ixy="-4.2369783e-11" ixz="-5.9381719e-09"
               iyy="1.1192413e-02" iyz="-1.4400107e-11"
               izz="2.0712558e-02" />
      </inertial>
  </link>








  <joint name="left_caster_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="left_caster_link"/>
    <origin xyz="-0.177 0.064 -0.02" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.04" upper="0" effort="1000" velocity="1000"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="left_caster_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="-1.57 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0.001 0" rpy="-1.57 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </visual>


    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.5" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0"
               izz="0.1" />
    </inertial>
  </link>



  <joint name="right_caster_joint" type="prismatic">
    <parent link="base_link"/>
    <child link="right_caster_link"/>
    <origin xyz="-0.177 -0.064 -0.02" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.04" upper="0" effort="1000" velocity="1000"/>
    <dynamics damping="0.0" friction="0.0"/>
  </joint>

  <link name="right_caster_link">
    <collision>
      <origin xyz="0 0.001 0" rpy="-1.57 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0.001 0" rpy="-1.57 0 0"/>
      <geometry>
        <sphere radius="0.02"/>
      </geometry>
    </visual>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.5" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0"
               iyy="0.1" iyz="0.0"
               izz="0.1" />
    </inertial>
  </link>








  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.064 0 0.122" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://turtlebot3_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.064 -0.065 0.094" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
       <mesh filename="package://turtlebot3_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.003 0.065 0.007" rpy="0 0 0"/>
      <geometry>
        <box size="0.012 0.132 0.020"/>
      </geometry>
    </collision>

    <!-- This inertial field needs doesn't contain reliable data!! -->
<!--   <inertial>
      <mass value="0.564" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
               iyy="0.000498940" iyz="0.0"
               izz="0.003879257" />
    </inertial>-->
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>




  <transmission name="wheel_left_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel_left_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel_left_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <transmission name="wheel_right_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="wheel_right_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="wheel_right_motor">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


  <transmission name="left_suspension_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_suspension_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_suspension_actuator">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_suspension_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_suspension_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_suspension_actuator">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="left_caster_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="left_caster_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="left_caster_actuator">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="right_caster_transmission">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="right_caster_joint">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="right_caster_actuator">
      <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


</robot>
